### ISSUE TITLE
Subscribing with Java client yields error

### ISSUE THREAD

**Issue by alnkpa** [zalando/nakadi-klients#52]
When calling `Client::subscribe` with empty stream parameters yields the following error:

```
[INFO] [05/27/2016 15:10:31.958] [Nakadi-Client-Connections-akka.actor.default-dispatcher-6] [akka://Nakadi-Client-Connections/user/EventReceivingActor-1464354631905] New subscription Subscribe(fulfillment-order-service.test.custom
er-shipment-order-created.merchant-center,/event-types/fulfillment-order-service.test.customer-shipment-order-created.merchant-center/events,None,org.zalando.nakadi.client.scala.EventHandlerImpl@36cf32e)
[INFO] [05/27/2016 15:10:31.960] [Nakadi-Client-Connections-akka.actor.default-dispatcher-6] [akka://Nakadi-Client-Connections/user/EventReceivingActor-1464354631905] Subscription nr 1 for eventType fulfillment-order-service.test.c
ustomer-shipment-order-created.merchant-center and listener 4532d31a-9427-4daa-93f
d-9ee4be23a046
[ERROR] [05/27/2016 15:10:32.659] [Nakadi-Client-Connections-akka.actor.default-dispatcher-5] [akka://Nakadi-Client-Connections/user/EventReceivingActor-1464354631905] None (of class scala.None$)
scala.MatchError: None (of class scala.None$)
        at org.zalando.nakadi.client.actor.SupervisingActor.subscribe(SupervisingActor.scala:117)
        at org.zalando.nakadi.client.actor.SupervisingActor$$anonfun$receive$1.applyOrElse(SupervisingActor.scala:97)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
        at org.zalando.nakadi.client.actor.SupervisingActor.aroundReceive(SupervisingActor.scala:87)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by kanuku** [comment]
Fixed in #53

**Comment by alnkpa** [comment]
Not fixed in newest version (alpha.8).

**Comment by kanuku** [comment]
Handling of parameters without Cursor will cause this error.

**Comment by kanuku** [comment]
@alnkpa Can you test it with version `2.0.0-pre-alpha.10`?
