### ISSUE TITLE
scala.MatchError: None (of class scala.None$)

### ISSUE THREAD

**Issue by dborovikov** [zalando/nakadi-klients#53]
**Client type:** Scala
**Client version:** 2.0.0-pre-alpha.7
**Environment:** nakadi-staging.aruha-test.zalan.do
**Description:** Match error in case of wrong buffer size
**Event-type:** asf_overarch_service_sql_v5_data_testing
**Error:**
```
12:10:57.002 [main] DEBUG o.z.nakadi.client.scala.ClientImpl - Subscribing listener id - cursor Some(Cursor(0,BEGIN)) - parameters StreamParameters(Some(Cursor(0,BEGIN)),Some(200),None,None,None,None,None) - eventType asf_overarch_service_sql_v5_data_testing - url /event-types/asf_overarch_service_sql_v5_data_testing/events
[INFO] [06/02/2016 12:10:57.013] [Nakadi-Client-Connections-akka.actor.default-dispatcher-5] [akka://Nakadi-Client-Connections/user/EventReceivingActor-1464862256977] New subscription SubscriptionKey(eventTypeName:asf_overarch_service_sql_v5_data_testing - partition:0)
[INFO] [06/02/2016 12:10:57.016] [Nakadi-Client-Connections-akka.actor.default-dispatcher-5] [akka://Nakadi-Client-Connections/user/EventReceivingActor-1464862256977] Subscription nr 1 for eventType asf_overarch_service_sql_v5_data_testing and listener id
subscribed on /event-types/asf_overarch_service_sql_v5_data_testing/events?batch_limit=200: Some(Cursor(0,BEGIN))
[ERROR] [06/02/2016 12:10:59.139] [Nakadi-Client-Connections-akka.actor.default-dispatcher-7] [akka://Nakadi-Client-Connections/user/EventReceivingActor-1464862256977/EventConsumingActor-0] onError - cursor null - SubscriptionKey(eventTypeName:asf_overarch_service_sql_v5_data_testing - Partition:0) - error Read 112948 bytes which is more than 40960 without seeing a line terminator
[INFO] [06/02/2016 12:10:59.141] [Nakadi-Client-Connections-akka.actor.default-dispatcher-7] [akka://Nakadi-Client-Connections/user/EventReceivingActor-1464862256977/EventConsumingActor-0] Shutting down subscription SubscriptionKey(eventTypeName:asf_overarch_service_sql_v5_data_testing - Partition:0) with listener-id id 
[INFO] [06/02/2016 12:10:59.148] [Nakadi-Client-Connections-akka.actor.default-dispatcher-8] [akka://Nakadi-Client-Connections/user/EventReceivingActor-1464862256977] ConsumingActor terminated EventConsumingActor-0
[INFO] [06/02/2016 12:10:59.150] [Nakadi-Client-Connections-akka.actor.default-dispatcher-8] [akka://Nakadi-Client-Connections/user/EventReceivingActor-1464862256977] Unsubscribe(UnsubscribeMsg(asf_overarch_service_sql_v5_data_testing,0,id))  
[INFO] [06/02/2016 12:10:59.153] [Nakadi-Client-Connections-akka.actor.default-dispatcher-8] [akka://Nakadi-Client-Connections/user/EventReceivingActor-1464862256977] Unsubscribing Listener : SubscriptionKey(eventTypeName:asf_overarch_service_sql_v5_data_testing - partition:0) from actor: Actor[akka://Nakadi-Client-Connections/user/EventReceivingActor-1464862256977/EventConsumingActor-0#-2041218748]
[INFO] [06/02/2016 12:10:59.157] [Nakadi-Client-Connections-akka.actor.default-dispatcher-8] [akka://Nakadi-Client-Connections/user/EventReceivingActor-1464862256977] Subscription nr 2 for eventType asf_overarch_service_sql_v5_data_testing and listener id
[ERROR] [06/02/2016 12:10:59.160] [Nakadi-Client-Connections-akka.actor.default-dispatcher-10] [akka://Nakadi-Client-Connections/user/EventReceivingActor-1464862256977] None (of class scala.None$)
scala.MatchError: None (of class scala.None$)
	at org.zalando.nakadi.client.actor.SupervisingActor.subscribe(SupervisingActor.scala:89)
	at org.zalando.nakadi.client.actor.SupervisingActor$$anonfun$receive$1.applyOrElse(SupervisingActor.scala:77)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
	at org.zalando.nakadi.client.actor.SupervisingActor.aroundReceive(SupervisingActor.scala:43)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.dungeon.DeathWatch$class.receivedTerminated(DeathWatch.scala:44)
	at akka.actor.ActorCell.receivedTerminated(ActorCell.scala:374)
	at akka.actor.ActorCell.autoReceiveMessage(ActorCell.scala:511)
	at akka.actor.ActorCell.invoke(ActorCell.scala:494)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Code:**
```scala
import java.net.URI

import com.fasterxml.jackson.core.`type`.TypeReference
import org.zalando.nakadi.client.scala.model.{ Cursor, EventStreamBatch }
import org.zalando.nakadi.client.scala.{ ClientError, Listener, StreamParameters }
import org.zalando.nakadi.client.utils.ClientBuilder
import org.zalando.stups.tokens.Tokens

object NakadiDemo extends App with Listener[GenericEvent] {
  val ACCCESS_TOKEN_URL = "https://token.services.auth.zalando.com/oauth2/access_token"

  val tokens = Tokens.createAccessTokensWithUri(new URI(ACCCESS_TOKEN_URL))
    .manageToken("token")
    .addScope("uid")
    .done()
    .start()

  val client = ClientBuilder()
    .withHost("nakadi-staging.aruha-test.zalan.do")
    .withSecuredConnection(true)
    .withVerifiedSslCertificate(false)
    .withTokenProvider(Some(() => tokens.get("token")))
    .build()

  val cursor = new Cursor("0", "BEGIN")
  client.subscribe[GenericEvent]("asf_overarch_service_sql_v5_data_testing", new StreamParameters(cursor=Some(cursor), batchLimit = Some(200)), this, new TypeReference[EventStreamBatch[GenericEvent]] {})

  override def id: String = "id"

  override def onError(endpoint: String, error: Option[ClientError]): Unit = {
    println(s"error in $endpoint: $error")
  }

  override def onSubscribed(endpoint: String, cursor: Option[Cursor]): Unit = {
    println(s"subscribed on $endpoint: $cursor")
  }

  override def onReceive(endpoint: String, cursor: Cursor, events: Seq[GenericEvent]): Unit = {
    println(s"got events from $endpoint: $events")
  }
}
```

**Comment by lukasniemeier-zalando** [comment]
@kanuku  we still seem to get this exception with `2.0.0-pre-alpha.8`

**Comment by kanuku** [comment]
Okay, thank you, I take a look at it now!
