### ISSUE TITLE
NoSuchFieldError: SNAKE_CASE

### ISSUE THREAD

**Issue by meamit** [zalando/nakadi-klients#73]
`Uncaught error from thread [Nakadi-Client-Connections-akka.actor.default-dispatcher-7] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[Nakadi-Client-Connections]
java.lang.NoSuchFieldError: SNAKE_CASE
	at org.zalando.nakadi.client.java.model.JavaJacksonJsonMarshaller$.defaultObjectMapper$lzycompute(JavaJacksonJsonMarshaller.scala:71)
	at org.zalando.nakadi.client.java.model.JavaJacksonJsonMarshaller$.defaultObjectMapper(JavaJacksonJsonMarshaller.scala:68)
	at org.zalando.nakadi.client.java.model.JavaJacksonJsonMarshaller$$anon$25.from(JavaJacksonJsonMarshaller.scala:64)
	at org.zalando.nakadi.client.scala.JavaEventHandlerImpl$$anonfun$2.apply(MessageHandler.scala:77)
	at org.zalando.nakadi.client.scala.JavaEventHandlerImpl$$anonfun$2.apply(MessageHandler.scala:77)
	at scala.util.Try$.apply(Try.scala:192)
	at org.zalando.nakadi.client.scala.JavaEventHandlerImpl.handleOnReceive(MessageHandler.scala:77)
	at org.zalando.nakadi.client.actor.ConsumingActor$$anonfun$receive$1.applyOrElse(ConsumingActor.scala:59)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at org.zalando.nakadi.client.actor.ConsumingActor.akka$stream$actor$ActorSubscriber$$super$aroundReceive(ConsumingActor.scala:41)
	at akka.stream.actor.ActorSubscriber$class.aroundReceive(ActorSubscriber.scala:182)
	at org.zalando.nakadi.client.actor.ConsumingActor.aroundReceive(ConsumingActor.scala:41)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)`

**Comment by meamit** [comment]
solved with:
`<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-core</artifactId>
    <version>2.7.3</version>
</dependency>

<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>2.7.3</version>
</dependency>

<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-annotations</artifactId>
    <version>2.7.3</version>
</dependency>`

**Comment by kanuku** [comment]
Hi, @meamit you need explicitly to add the jackson dependencies version to your path. 
Otherwise the client will try to uses whatever dependency it finds in the path. In this case it is a jackson dependency that is missing a field.

Just add the two lines below to your pom:
```xml
...
  <dependency>
    <groupId>org.zalando.nakadi.client</groupId>
    <artifactId>nakadi-klients</artifactId>
    <version> *version* </version>
  </dependency>
  <dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>2.7.3</version>
  </dependency>
  <dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-core</artifactId>
    <version>2.7.3</version>
  </dependency>
...
```
